In [1]:
# documentation: https://opensource.com/article/21/9/python-numpy
# numpy is numbers, time, and math for python
import numpy as np
import time as time

my_list = range(1, 1000000000)
len(my_list)

999999999

In [2]:
# Finding the minimum value, by python asking every item if its the smallest item.  Rather inefficient, especially for larger datasets.  Draws a lot of memory to run function.
start = time.time()
min(my_list)

print('Time elapsed in milliseconds: ' + str((time.time() - start) * 1000))

Time elapsed in milliseconds: 96127.19058990479


In [3]:
# same as above, but within a range.  So it will only ask for smallest within the range.  Much quicker.
# Good for setting programs to run at intervals, so big data pull doesn't happen all at once.Helps with rate limited issues on websites, look like doing it by hand when scrapping.

my_list = np.arange(1, 1000000000)

# Grabs time when it gets to the minimum, how log it took to make the lsit.  Checks time right before and right after.
start = time.time()
my_list.min()

print('Time elapsed in milliseconds: ' + str((time.time() - start) * 1000))

In [9]:
# Building multi dimensional (md) arrays.  This is so you can use arrays with numpy.
my_ndarray = np.array([1, 2, 3, 4, 5])
print(my_ndarray)
# This is a type check, in this case confirming it is a numpy md array.
type(my_ndarray)

[1 2 3 4 5]


numpy.ndarray

In [11]:
# Creating lists with np md arrays
np.shape(my_ndarray)
# 2 sets of 3 items, there for its shape is 2, 3. 
my_ndarray2 = np.array([(1, 2, 3), (4, 5, 6)])
np.shape(my_ndarray2)

(2, 3)

In [16]:
my_ndarray.dtype
# How much stuff is in the array
my_ndarray.size

5

In [13]:
# Irem's relationship to one another, determined by largest item in the set.   Integers, whole numbers are simpleist way.  As soon as decimal is involved, all numbers are floats and things get more complicated.
my_ndarray2 = np.array([1, 2.0, 3])
print(my_ndarray2)
my_ndarray2.dtype

[1. 2. 3.]


dtype('float64')

In [14]:
# A string screws it up too
my_ndarray2 = np.array([1, '2', 3])
print(my_ndarray2)
my_ndarray2.dtype
# u11 measn it can't compute beccause it is a string

['1' '2' '3']


dtype('<U11')

In [17]:
# Creating boxes for arrays, 2 sets of 3 items in each.  Minesweeper grid.
my_ndarray = np.zeros([2,3], dtype=int)
print(my_ndarray)

[[0 0 0]
 [0 0 0]]


In [18]:
# As above, but filling boxes with 10.  Good for starting structural data
my_ndarray = np.full([2,3], 10, dtype=int)
print(my_ndarray)

[[10 10 10]
 [10 10 10]]


In [19]:
# Diagonal array needs, like multiplication 
my_ndarray = np.eye(3, dtype=int)
print(my_ndarray)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [21]:
# a range function that fills on intervals
my_ndarray = np.arange(1, 20, 3)
print(my_ndarray)
print(my_ndarray[2:4])

[ 1  4  7 10 13 16 19]
[ 7 10]


In [22]:
# array generaato with intervals
my_ndarray[-1:] = 100
print(my_ndarray)

[  1   4   7  10  13  16 100]


In [24]:
# Adding subtracting and multiplying arrays
# first 2 lines define the arrays, last 3 run the math problems.  Useful for text analysis of term freq accross a number of texts.  Freq of monster times the 3 books
my_ndarray = np.array([1, 2, 3, 4, 5])
my_ndarray2 = np.array([6, 7, 8, 9, 10])

print(my_ndarray2 + my_ndarray)
print(my_ndarray2 - my_ndarray)
print(my_ndarray2 * my_ndarray)


[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]


In [25]:
# Sorts values from out of order to in order
my_ndarray = np.array([3, 1, 2, 5, 4])
my_ndarray.sort()
print(my_ndarray)

[1 2 3 4 5]


In [26]:
# As above, but with maintaining original out of order array
my_ndarray = np.array([3, 1, 2, 5, 4])
print(np.sort(my_ndarray))
print(my_ndarray)

[1 2 3 4 5]
[3 1 2 5 4]
